Organizations:
    - &Org3
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: $[orgName]

        # ID to load the MSP definition as
        ID: $[orgName]

        MSPDir: $[mspPath]

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: $[host]
              Port: $[port]